type Query {
  info: String!,
  restaurants: [Restaurant!]
  getRestaurantByName(name: String!): Restaurant!
}

type Player {
  name: String!
  message: String
}

type Restaurant {
    name: String!
    open: Boolean!
    categories: [String!]!
    stars: Float
    full_address: String!
    photo_url: String!
    price: Float
}

type Mutation {
  createPlayer(name: String!): Player!
  getPlayer(name: String!): Player!
  createRestaurant(name: String!, open: Boolean!, categories: [String!]!, stars: Float, full_address: String!, photo_url: String!, price: Float!): Restaurant!
}
